server:
  port: 7000

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.80.130:3306/zshop_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: zshop-coupon

#classpath加不加*的区别在于加*会把 第三方jar包类路径下匹配到的xml文件也进行包扫描
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
