server:
  port: 80
spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.80.130:3306/zshop_pms
#    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: zshop-gateway
  redis:
    host: 192.168.80.130
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        # /api/product路径的路由到product微服务
        - id: product_route
          uri: lb://zshop-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 前端项目的所有路径都路由到renren-fast
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        # nginx 转发至网关  由网关分发  要放置最后
#        - id: zshop_host_route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}



